### ISSUE TITLE
Describe the metadata dictionary's typing constraints in SerializableObjet

### ISSUE THREAD

**Issue by reinecke** [sandflow/otio-core-specification#5]
All SerializableObjects have a metadata dictionary.
These dictionaries adhere to typing constraints very similar to json: 

- all keys must be strings
- values can be: string, integer, double, dictionary, array, boolean, null
- values can also be other SerializableObjects

**Comment by palemieux** [comment]
> These dictionaries adhere to typing constraints very similar to json:

Aren't the constraints exactly those of JSON? If not, what are the differences?

> values can also be other SerializableObjects

`SerializableObjects` are specialization of `dictionary`. Is there a reason to call them out explicitly?

**Comment by reinecke** [comment]
The reason I say similar is because (if I remember correctly) json is not explicit about float vs. double precision. In OTIO we require double precision.

On the metadata dictionary front, I only call out `SerializableObject` explicitly because it is expected that implementations should deeply traverse metadata dictionaries to explicitly handle OTIO objects that may be within.

**Comment by palemieux** [comment]
>  only call out SerializableObject explicitly because it is expected that implementations should deeply
> traverse metadata dictionaries to explicitly handle OTIO objects that may be within.

How would an implementation differentiate between an OTIO object and a plain dictionnary?

What scenarios would result in OTIO objects being stored as metadata -- instead of within the OTIO timeline hierarchy?

**Comment by palemieux** [comment]
Also, it looks like the reference software does not detect that members of `metadata` are OTIO objects:

https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/master/src/opentimelineio/anyDictionary.h

**Comment by reinecke** [comment]
In practical testing, it looks like the reference implementation does support deserializing supported schema items deeply from metadata dictionaries:

```
>>> bin = otio.schema.SerializableCollection()
>>> marker = otio.schema.Marker(name="my marker", color="GREEN")
>>> bin.metadata["top_dictionary"] = {"nested_marker": marker}
>>> otio.adapters.write_to_file(bin, "/tmp/test.otio")
True
>>> bin2 = otio.adapters.read_from_file("/tmp/test.otio")
>>> bin2.metadata["top_dictionary"]["nested_marker"]
otio.schema.Marker(name='my marker', marked_range=otio.opentime.TimeRange(start_time=otio.opentime.RationalTime(value=0, rate=1), duration=otio.opentime.RationalTime(value=0, rate=1)), metadata={})
>>> bin2.metadata["top_dictionary"]["nested_marker"].color
'GREEN'
```

I believe the implementation for it is here:
https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/2c2ac4daa37936cae1a14a4ae94404168a541346/src/opentimelineio/deserialization.cpp#L122-L126

And further down here:
https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/master/src/opentimelineio/deserialization.cpp#L401-L473

If my assumption is correct then `EndObject` is called each time a JSON object is closed, which would happen in a depth-first pattern. At that time, if a json object contained the `OTIO_SCHEMA` key, the system will deserialize the dictionary using normal otio schema resolution, otherwise it remains an `AnyDictionary`. This same mechanism also allows `RationalTime`, `TimeRange`, and `TimeTransform` to be stored richly in these dictionaries.

The most common scenarios in which schema items are stored in the `metadata` dictionary are for `RationalTime` and `TimeRange`, however I know Pixar has an internal schema they use to store their production tracking metadata. This also provides a mechanism trial workflows where rich schema data might be stored in the `metadata` dictionary as a transitional step before amending the official schema to include a new "first-class" attribute.

**Comment by palemieux** [comment]
@reinecke See proposed text at #14
